// apps/docs/src/lib/demos/components/core/vue/button/sizes.vue
<script setup lang="ts">
import Button from '@/lib/components/core/default/vue/button.vue';
</script>

<template>
    <div className="flex w-full items-center justify-center gap-4">
      <Button size="sm">Button</Button>
      <Button size="md">Button</Button>
      <Button size="lg">Button</Button>
    </div>
</template>

// apps/docs/src/lib/demos/components/core/number-field/sizes.tsx
import { NumberField } from "@/lib/components/core/default/number-field";

export default function Demo() {
  return (
    <div className="flex items-center gap-4">
      <NumberField placeholder="small (sm)" size="sm" />
      <NumberField placeholder="medium (md)" size="md" />
      <NumberField placeholder="large (lg)" size="lg" />
    </div>
  );
}
