// apps/docs/src/lib/demos/components/core/vue/button/prefix-and-suffix.vue
<script setup lang="ts">
import Button from '@/lib/components/core/default/vue/button.vue';
import { UploadIcon } from "@/lib/icons";
</script>

<template>
  <div className="flex items-center gap-2">
    <Button :prefix="UploadIcon">
      Button
    </Button>
    <Button :suffix="UploadIcon">
      Button
    </Button>
  </div>
</template>

// apps/docs/src/lib/demos/components/core/color-field/prefix-and-suffix.tsx
import { ColorField } from "@/lib/components/core/default/color-field";
import { PaletteIcon } from "@/lib/icons";

export default function Demo() {
  return (
    <div className="flex flex-col items-center gap-4">
      <ColorField prefix={<PaletteIcon />} />
      <ColorField suffix={<PaletteIcon />} />
    </div>
  );
}
