// apps/docs/src/lib/demos/components/core/search-field/loading.tsx
import React from "react";
import { SearchField } from "@/lib/components/core/default/search-field";

export default function Demo() {
  return (
    <div className="flex items-center gap-4">
      <SearchField isLoading loaderPosition="prefix" />
      <SearchField isLoading loaderPosition="suffix" />
    </div>
  );
}

// apps/docs/src/lib/demos/components/core/vue/button/loading.vue
<script setup lang="ts">
import Button from '@/lib/components/core/default/vue/button.vue';
import { ref } from 'vue';
const someVariable = ref(5);
</script>

<template>
  <div className="flex w-full items-center justify-center gap-2">
    <Button size="sm" :isLoading="someVariable === 5">
      Button
    </Button>
    <Button size="md" isLoading>
      Button
    </Button>
    <Button size="lg" isLoading>
      Button
    </Button>
  </div>
</template>
