// apps/docs/src/lib/demos/components/core/angular/button/prefix-and-suffix.ts
import { Component } from '@angular/core';
import { HlmButtonModule } from '@/lib/components/core/default/angular/button/hlm-button.module';
import { UploadIconComponent } from '@/lib/components/core/default/angular/lib/icons/icons';

@Component({
  selector: 'button-preview',
  standalone: true,
  imports: [HlmButtonModule],
  template: `
  <div className="flex items-center gap-2">
    <Button hlmBtn [prefix]="UploadIconComponent">
      Button
    </Button>
    <Button hlmBtn [suffix]="UploadIconComponent">
      Button
    </Button>
  </div>
  `,
  
})

export class ButtonPreviewComponent {
  UploadIconComponent = UploadIconComponent;
}

// apps/docs/src/lib/demos/components/core/vue/button/prefix-and-suffix.vue
<script setup lang="ts">
import Button from '@/lib/components/core/default/vue/button.vue';
import { UploadIcon } from "@/lib/icons";
</script>

<template>
  <div className="flex items-center gap-2">
    <Button :prefix="UploadIcon">
      Button
    </Button>
    <Button :suffix="UploadIcon">
      Button
    </Button>
  </div>
</template>
