// apps/docs/src/lib/demos/components/core/react/button/sizes.tsx
import { Button } from "@/lib/components/core/default/react/button";

export default function Demo() {
  return (
    <div className="flex w-full items-center justify-center gap-4">
      <Button size="sm">Button</Button>
      <Button size="md">Button</Button>
      <Button size="lg">Button</Button>
    </div>
  );
}

// apps/docs/src/lib/demos/components/core/vue/button/sizes.vue
<script setup lang="ts">
import Button from '@/lib/components/core/default/vue/button.vue';
</script>

<template>
    <div className="flex w-full items-center justify-center gap-4">
      <Button size="sm">Button</Button>
      <Button size="md">Button</Button>
      <Button size="lg">Button</Button>
    </div>
</template>
